---
on:
  workflow_call:
    secrets:
      OL_HQ_PROJECT_SECRET:
        required: true

jobs:
  assign_to_ol_hq:
    runs-on: ubuntu-latest
    name: Assign New Issues to Open Learning HQ
    if: github.event.action == 'opened' && github.event.issue
    steps:
    - uses: actions/add-to-project@v0.4.0
      with:
        project-url: https://github.com/orgs/mitodl/projects/21
        github-token: ${{ secrets.OL_HQ_PROJECT_SECRET }}

  

  